/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.io.*;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import javax.swing.DefaultListModel;
/**
 *
 * @author ejziel.santos
 */
public class viewAmistoso extends javax.swing.JFrame {
 
    /**
     * Creates new form ZikaFut
     */
    public viewAmistoso() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldTimeA = new javax.swing.JTextField();
        jTextFieldTimeB = new javax.swing.JTextField();
        jLabelX = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListJogadoresA = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListJogadoresB = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPartida = new javax.swing.JList<>();
        jTextFieldPlacarTimeA = new javax.swing.JTextField();
        jTextFieldPlacarTimeB = new javax.swing.JTextField();
        jLabelImagemA = new javax.swing.JLabel();
        jLabelImagemB = new javax.swing.JLabel();
        jLabelEstadio = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListStarA = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListStarB = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBInicarGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));

        jTextFieldTimeA.setEditable(false);
        jTextFieldTimeA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldTimeA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldTimeB.setEditable(false);
        jTextFieldTimeB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldTimeB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelX.setText("X");

        jScrollPane1.setViewportView(jListJogadoresA);

        jScrollPane2.setViewportView(jListJogadoresB);

        jListPartida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(jListPartida);

        jTextFieldPlacarTimeA.setEditable(false);
        jTextFieldPlacarTimeA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldPlacarTimeA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldPlacarTimeB.setEditable(false);
        jTextFieldPlacarTimeB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldPlacarTimeB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelImagemA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagemA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/bola.png"))); // NOI18N
        jLabelImagemA.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabelImagemA.setName(""); // NOI18N

        jLabelImagemB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/bola2.png"))); // NOI18N
        jLabelImagemB.setMaximumSize(new java.awt.Dimension(200, 200));

        jLabelEstadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstadio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jScrollPane4.setViewportView(jListStarA);

        jScrollPane5.setViewportView(jListStarB);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Escalação:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Escalação:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Estrela:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Estrela:");

        jLabel5.setFont(new java.awt.Font("DokChampa", 0, 60)); // NOI18N
        jLabel5.setForeground(java.awt.Color.blue);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/zikafoot32.png"))); // NOI18N
        jLabel5.setText("ZikaFoot 2020");
        jLabel5.setMinimumSize(new java.awt.Dimension(0, 0));

        jBInicarGame.setText("INICIAR");
        jBInicarGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicarGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabelEstadio, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelImagemA, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTimeA))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPlacarTimeA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelX)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldPlacarTimeB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelImagemB, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addComponent(jTextFieldTimeB))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBInicarGame))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImagemB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImagemA, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTimeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPlacarTimeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTimeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPlacarTimeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelX)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEstadio, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jBInicarGame))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicarGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicarGameActionPerformed
        // TODO add your handling code here:
        //Carregando Amistoso
        Amistoso friendly = new Amistoso();    
        //Fim carregar amistoso
            
            jTextFieldTimeA.setText(friendly.getTimeA().getNome());
            jTextFieldTimeB.setText(friendly.getTimeB().getNome());
            jLabelImagemA.setIcon(friendly.getTimeA().getLogo());
            jLabelImagemB.setIcon(friendly.getTimeB().getLogo());
            jLabelEstadio.setText(friendly.getTimeA().getEstadio());
            
            int aux;
            
            if(friendly.getTimeA().sizePlayer() < 11){
                aux = friendly.getTimeA().sizePlayer();
            }else{
                aux = 11;
            }
            
            DefaultListModel lista = new DefaultListModel();
                jListJogadoresA.setModel(lista);
            for(int i=0;i<aux;i++){   
                lista.addElement(friendly.getTimeA().getPlayer(i).getNome());
            }
            
            DefaultListModel starList = new DefaultListModel();
                jListStarA.setModel(starList);
            for(int i=0;i<aux;i++){   
                starList.addElement(String.valueOf(friendly.getTimeA().getPlayer(i).getEstrela()));
            }
            
            if(friendly.getTimeB().sizePlayer() < 11){
                aux = friendly.getTimeB().sizePlayer();
            }else{
                aux = 11;
            }
            
            DefaultListModel lista2 = new DefaultListModel();
                jListJogadoresB.setModel(lista2);
            for(int i=0;i<aux;i++){   
               lista2.addElement(friendly.getTimeB().getPlayer(i).getNome());
            }
            
            DefaultListModel starList2 = new DefaultListModel();
                jListStarB.setModel(starList2);
            for(int i=0;i<aux;i++){   
                starList2.addElement(String.valueOf(friendly.getTimeB().getPlayer(i).getEstrela()));
            }
            
            
            
            friendly.jogar(jListPartida);
            
            
            jTextFieldPlacarTimeA.setText(String.valueOf(friendly.getPlacarTimeA()));
            jTextFieldPlacarTimeB.setText(String.valueOf(friendly.getPlacarTimeB()));
    }//GEN-LAST:event_jBInicarGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAmistoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
   
        
        
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZikaFut().setVisible(true);
            }       
        });       
        */
        
        
        //</editor-fold>
        
   
        
        
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZikaFut().setVisible(true);
            }       
        });       
        */
        
        
        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInicarGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEstadio;
    private javax.swing.JLabel jLabelImagemA;
    private javax.swing.JLabel jLabelImagemB;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JList<String> jListJogadoresA;
    private javax.swing.JList<String> jListJogadoresB;
    private javax.swing.JList<String> jListPartida;
    private javax.swing.JList<String> jListStarA;
    private javax.swing.JList<String> jListStarB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextFieldPlacarTimeA;
    private javax.swing.JTextField jTextFieldPlacarTimeB;
    private javax.swing.JTextField jTextFieldTimeA;
    private javax.swing.JTextField jTextFieldTimeB;
    // End of variables declaration//GEN-END:variables
}
